In [ ]:
import numpy as np

In [72]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
A.reshape(3, -1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [149]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
A[A % 2 != 0] = -1
A

# Alternatively
# a[np.where(a%2!=0)] = -1
# Where returns array of indices
# while the above returns array of bool

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

🔴 Read on "where" in numpy🔴

In [147]:
X = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
Y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

np.where(X > Y)

(array([1, 2, 4, 5, 6, 7, 8, 9]),)

In [148]:
np.where(X == Y)

(array([0]),)

In [67]:
A = np.arange(100).reshape(5,-1)
A[:, :4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

### Additional Problems

In [111]:
A = np.random.randint(30, high=41, size=10)
A

array([33, 38, 34, 33, 40, 38, 38, 35, 33, 38])

In [131]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
B = np.array([[7, 8, 10] ,[4, 5, 6], [1, 2, 3]])
C = A + B
E = A - B

print(C)
print()
print(E)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]

[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]


In [140]:
print(np.sum(a))              # all ele sum
print(np.sum(b, axis=0))      # column wise sum ,i.e, row output
print(np.sum(c, axis=1))      # row wise sum    ,i.e, column ouput

46
[12 15 19]
[31 30 31]


In [141]:
D = A @ B
D

array([[ 18,  24,  31],
       [ 54,  69,  88],
       [ 91, 116, 148]])

In [142]:
E = np.sort(C)
E

array([[ 8, 10, 13],
       [ 8, 10, 12],
       [ 8, 10, 13]])

In [143]:
E = np.transpose(E)
E

# or simply E.T

array([[ 8,  8,  8],
       [10, 10, 10],
       [13, 12, 13]])