In [46]:
import numpy as np

1. Convert a 1-D array into a 2-D array with 3 rows.  
Start with:  
Assign-1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])  
Desired output:  
[[ 0, 1, 2]  
[3, 4, 5]  
[6, 7, 8]]  

In [47]:
b = np.arange(0, 9)
b.shape = (3, -1)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

2. Replace all odd numbers in the given array with -1  
Start with:  
Assign-2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  
Desired output:  
[ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1] 

In [48]:
a = np.arange(0, 10)
odd_mask = (a & 1) == 1
a[odd_mask] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

3. Find the positions of:  
  
elements in x where its value is more than its corresponding element in y, and  
elements in x where its value is equals to its corresponding element in y. 

In [49]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
print(np.where(x > y))
print(np.where(x == y))

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


4. Extract the first four columns of this 2-D array.  

In [50]:
a = np.arange(100).reshape(5, -1)
print(a[:, :4])

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


### Additional Questions

1. Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive).

In [51]:
a = np.random.randint(30, 40, (10, ))
a

array([37, 39, 32, 38, 34, 33, 34, 36, 34, 37], dtype=int32)

2. Consider the following matrices :  
A= ((1, 2, 3), (4, 5, 6), (7, 8, 10)) and   B = ((7, 8, 10) ,(4, 5, 6), (1, 2, 3))  
Write a python program to perform the following using Numeric Python (numpy).  
i) Add and Subtract of the Matrix A and B, print the resultant matrix C for add and E for subtract.  
ii) Compute the sum of all elements of Matrix A, sum of each column of Matrix B and sum of each row of Matrix C  
iii) Product of two matrices A and B, and print the resultant matrix D  
iv) Sort the elements of resultant matrix C and print the resultant Matrix E.                             
v) Transpose the Matrix E and print the result  

In [52]:
a = np.array(((1, 2, 3),
              (4, 5, 6),
              (7, 8, 10)))
b = np.array(((7, 8, 10),
              (4, 5, 6),
              (1, 2, 3)))
print(f'a:\n{a}')
print(f'\nb:\n{b}')

a:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]

b:
[[ 7  8 10]
 [ 4  5  6]
 [ 1  2  3]]


In [53]:
c = a + b
e = a - b
print(f'c:\n{c}')
print(f'\ne:\n{e}')

c:
[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]

e:
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]


In [54]:
print(a.sum())  # all elements sum of A
print(b.sum(axis=0))  # column wise sum of B
print(c.sum(axis=1))  # row wise sum of C


46
[12 15 19]
[31 30 31]


In [55]:
d = a @ b
print(d)

[[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]


In [56]:
c.sort(kind='stable')
print(c)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]


In [57]:
e.T

array([[-6,  0,  6],
       [-6,  0,  6],
       [-7,  0,  7]])