In [1]:
import numpy as np

Question 1

In [2]:
A = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
A.reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Question 2

In [3]:
B = A.copy()
B[B % 2 == 1] = -1
B

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

Question 3

In [4]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

print(np.where(x > y))
print(np.where(x == y))

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


Question 4

In [5]:
A = np.arange(100).reshape(5,-1)
A[:, :4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

Additional question 1

In [6]:
np.random.randint(30, 41, 10)

array([38, 39, 40, 37, 39, 39, 31, 30, 34, 32], dtype=int32)

Additional question 2

In [7]:
A = ((1, 2, 3), (4, 5, 6), (7, 8, 10))
B = ((7, 8, 10) ,(4, 5, 6), (1, 2, 3))

A = np.array(A)
B = np.array(B)

C = A + B
D = A - B

print(C)
print(D)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]


In [8]:
A @ B

array([[ 18,  24,  31],
       [ 54,  69,  88],
       [ 91, 116, 148]])

In [9]:
print(np.sum(A))
print(np.sum(B, axis=1))
print(np.sum(C, axis=0))

46
[25 15  6]
[24 30 38]


In [10]:
E = np.sort(C)
E

array([[ 8, 10, 13],
       [ 8, 10, 12],
       [ 8, 10, 13]])

In [11]:
E.T

array([[ 8,  8,  8],
       [10, 10, 10],
       [13, 12, 13]])